export const ALL_ATTRIBUTE_REQUEST = "ALL_ATTRIBUTE_REQUEST";
export const ALL_ATTRIBUTE_SUCCESS = "ALL_ATTRIBUTE_SUCCESS";
export const ALL_ATTRIBUTE_FAIL = "ALL_ATTRIBUTE_FAIL";

export const CREATE_ATTRIBUTE_REQUEST = "CREATE_ATTRIBUTE_REQUEST";
export const CREATE_ATTRIBUTE_SUCCESS = "CREATE_ATTRIBUTE_SUCCESS";
export const CREATE_ATTRIBUTE_RESET = "CREATE_ATTRIBUTE_RESET";
export const CREATE_ATTRIBUTE_FAIL = "CREATE_ATTRIBUTE_FAIL";

export const UPDATE_ATTRIBUTE_REQUEST = "UPDATE_ATTRIBUTE_REQUEST";
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS";
export const UPDATE_ATTRIBUTE_RESET = "UPDATE_ATTRIBUTE_RESET";
export const UPDATE_ATTRIBUTE_FAIL = "UPDATE_ATTRIBUTE_FAIL";

export const DELETE_ATTRIBUTE_REQUEST = "DELETE_ATTRIBUTE_REQUEST";
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS";
export const DELETE_ATTRIBUTE_RESET = "DELETE_ATTRIBUTE_RESET";
export const DELETE_ATTRIBUTE_FAIL = "DELETE_ATTRIBUTE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
